### ISSUE TITLE
Mismatch of bond type between SDF and MOL2 format

### ISSUE THREAD

**Issue by junepark6** [openbabel/openbabel#2415] opened 2021-10-07 20:16 UTC
## Environment Information
Open Babel version:3.1.1
Operating system and version:
CentOS Linux 7.0

## Expected Behavior

I expected that all bond types are same between SDF and MOL2.

## Actual Behavior

I attached the PNG file below. 
In SDF, highlighted carbon has 4 connectivities, whereas it has 5 connectivities in MOL2. 

## Steps to Reproduce

First of all, I downloaded MYU from RCSB through command "wget https://files.rcsb.org/ligands/view/MYU_ideal.sdf".
Secondly, I transformed it into MOL2 through command "obabel -isdf MYU_ideal.sdf -omol2 -O test.mol2". 

![sdf_mol2](https://user-images.githubusercontent.com/19364283/136455885-f556c99e-bab0-4cd7-a6c9-e67625521f0e.png)

**Comment by nbehrnd** [comment] 2021-10-10 18:11
Equally "chemically speaking, the same result" if you convert the .sdf
or the .mol2 by OpenBabel itself into .png, too.

**Comment by ghutchis** [comment] 2021-10-10 19:37
As @nbehrnd has pointed out, I don't see this as an Open Babel error. The `mol2` format is supposed to indicate aromatic bonds. I haven't seen any formal definition of a `mol2 aromaticity model` but I'd certainly consider that an aromatic fragment.

So then the question is how to depict the ring structure? Well, as @nbehrnd points out, it works fine in `jmol` and here's the depiction from Avogadro (which uses Open Babel under the hood)

<img width="502" alt="Screen Shot 2021-10-10 at 3 30 31 PM" src="https://user-images.githubusercontent.com/41128/136710545-93007ff6-618e-4a18-be22-6590e2eb3ef6.png">

I'm closing this as "not a bug" in Open Babel.

**Closed by ghutchis** 2021-10-10 19:37 UTC
Labels: not-a-bug
