### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by iwatobipen** [openbabel/openbabel#203] opened 2015-07-20 06:40 UTC
Dear,
I tried to install openbabel using following command.
"conda install -c https://conda.binstar.org/patrickfuller openbabel"
Python biding works well, but when I tried to import pybel segmentation fault was occurred.
Like this.
In [1]: import openbabel # no problem

In [2]: import pybel # error..
/Users/usr1/.pyenv/versions/anaconda-2.2.0/bin/python.app: line 3:  3970 Segmentation fault: 11  /Users/usr1/.pyenv/versions/anaconda-2.2.0/python.app/Contents/MacOS/python "$@"

If possible, would you please advice me to fix the problem.
Thank you

**Comment by ghutchis** [comment] 2015-07-23 19:11
My guess is that the conda install isn't properly linking against your anaconda version of python on your Mac. On the terminal, run `otool -L /Users/usr1/.pyenv/versions/anaconda-2.2.0//usr/local/anaconda/lib/python2.7/site-packages/_openbabel.so`

My guess is that it's linked to the /System Python framework.

**Comment by iwatobipen** [comment] 2015-07-26 08:14
Dir ghutchis,
Thank you for your advice.
I checked link using otool command and I got following output.
$ otool -L /Users/usr1/.pyenv/versions/anaconda-2.2.0/lib/python2.7/site-packages/_openbabel.so
/Users/usr1/.pyenv/versions/anaconda-2.2.0/lib/python2.7/site-packages/_openbabel.so:
	@rpath/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	@rpath/libopenbabel.4.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)

Is path of libopenbabel.4.dylib wrong?
I changed @rpath/liboenbabel.4.dylib to .pyenv/versions/anaconda-2.2.0/lib/libopenbabel.4.dylib using install_name_tool.
But not work well.

**Comment by ghutchis** [comment] 2015-07-30 02:14
Actually, I take that back.. If you import openbabel, it's fine? Can you run some code with ob and not with pybel?

**Comment by ghutchis** [comment] 2015-07-30 02:14
Paging @baoilleach - any idea what would cause a crash with pybel and not "import openbabel"?

**Comment by baoilleach** [comment] 2015-07-30 06:41
Importing pybel instantiates an OBConversion and gets the list of formats. I'd presume that any non-trivial 'openbabel' script would trigger the same problem. So it could be that the plugins aren't found.

**Comment by tantrev** [comment] 2015-11-04 07:19
I also get this same segmentation fault error when importing pybel.  My otool -L output is as follows:

/Users/owner/anaconda/lib/python2.7/site-packages/_openbabel.so:
	@rpath/libpython2.7.dylib (compatibility version 2.7.0, current version 2.7.0)
	@rpath/libopenbabel.4.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)

**Comment by getmolmap** [comment] 2015-11-23 08:28
Reproduced both on Intel and AMD pc with LMDE2 in the latest python 3.4 conda environment:
>>> import pybel
Segmentation fault

However, importing opnbabel works fine.
When I install openbabel and python bindings from packages, it works without problem with the system's python2.7, but not in the conda environments.

Advice on diagnosis and/or workaround would be appreciated.

**Comment by fredrikw** [comment] 2015-11-23 13:06
Hi,

My suggestion when working in the conda environment is to use the conda-packages for openbabel that have been supplied by various users. E.g. patrickfuller/openbabel (see below)

Otherwise, you really need to make sure that all cmake variables are set correctly to have openbabel compile against the conda python.

Kind regards,
Fredrik

[Fredriks-MBP] > anaconda show patrickfuller/openbabel
Using anaconda-server api site https://api.anaconda.org
Name:    openbabel
Summary: A chemical toolbox designed to speak the many languages of chemical data
Access:  public
Package Types:  conda
Versions:
   + 2.3.90

To install this package with conda run:
     conda install --channel https://conda.anaconda.org/patrickfuller openbabel

**Comment by getmolmap** [comment] 2015-11-23 14:22
@fredrikw 
Greetings,
Thanks for the quick reply!
I have exhausted the available 6 conda-package options for linux-64 platforms with the same uninformative error message. (segmentation fault)
How do I list all cmake variables to set?

A bit of user level info: I'm using mostly linux (LMDE2) and I have compiled a few chemistry program packages before and I know it is seldom easy. I use Python + numpy but I don't "speak" other languages.

**Comment by Huitzilo** [comment] 2015-11-24 21:27
Chiming in here because I've run in this issue today too. I reported a similar issue in the old sourceforge issue tracker a while ago (which was probably already abandoned by then): https://sourceforge.net/p/openbabel/bugs/916/ .

I was trying to compile openbabel from source on OSX, using the anaconda python distribution to link against. I used the cmake options `-DPYTHON_BINDINGS=ON -DRUN_SWIG=ON -DPYTHON_INCLUDE_DIR=~/anaconda/include/python2.7/ -DPYTHON_LIBRARY=~/anaconda/lib/libpython2.7.dylib` 

Importing pybel results in 

    Fatal Python error: PyThreadState_Get: no current thread
    Abort trap: 6

Running  `otool -L _openbabel.so` shows that `libpython2.7.dylib` is linked without any prefixed path.
The problem can be fixed using `install_name_tool -change libpython2.7.dylib /Users/micha/anaconda/lib/libpython2.7.dylib`, i.e. providing the full path to the anaconda libpython.

I reproduced this problem today on a fresh checkout of openbabel. BTW, installing openbabel from @patrickfuller 's conda channel also results in a segfault (which is why I resorted to compiling from source in the first place).

Is there a way to have cmake instruct the linker to use the full path of `libpython2.7.dylib` as provided on the command line? This would greatly facilitate compiling pybel from source on OSX.

**Comment by fredrikw** [comment] 2015-11-25 06:06
Hi,

All this trouble you need to go through to install from source with anaconda python was why I suggested the packages, but I haven’t run them myself in a while so I didn’t no that they posed problems in themselves. Anyway, the/a problem with the anaconda python, at least on OS X is that they don’t specify the full path or not even an @rpath at installation. The dynamic linkage in OS X is set up to use the install_name of the library when linking and since anaconda’s libpython is named only libpython2.7.dylib you need to change that to the full name using install_name_tool. This can be made either to the openbabel library or to the libpython library. In the latter case, you need to do this before building open babel and you probably need to redo it after conda python is updated. In the former case, you need to change this everytime you compile open babel.

Unfortunately, I don’t know enough of the linking process in Linux to tell what the corresponding workflow would be for getmolmap...

Kind regards,
Fredrik

**Comment by tantrev** [comment] 2015-11-25 06:37
Perhaps we can summon @patrickfuller?

**Comment by fredrikw** [comment] 2015-11-25 09:55
I think it should be possible to run ldd in Linux to get the dynamic libraries used for a .so so you could run `ldd _openbabel.so` and see what it's linked against and compare to your python binary.
Looking back in the thread I would also get back to Noel's comment on pybel vs. openbabel loading. If you can import openbabel but not pybel, try to instantiate an obconversion object and then load some formats to see if that is what is actually causing the segfault. In that case, all this linkage work probably  won't help...
My final pease of advise for earlier posts would be that if `otool -L` shows entries with `@rpath/...` it can be an idea to check what `otool -l` shows as explained in http://stackoverflow.com/a/12522096/328879

**Comment by Huitzilo** [comment] 2015-11-25 10:20
Hi @fredrikw , thanks for the hint regarding `otool -l`. Interestingly, I wasn't able to find any `LC_RPATH` commands in the dylib images, even if `otool -L` shows that libs are linked with `@rpath` definition. In my case this affects libcairo, which is linked as `@rpath/./libcairo.2.dylib`. Of course, without an `@rpath` defined the lib can't be found and hence not loaded (leading to loss of functionality, for which I actually wanted to create another issue). Does this qualify as a bug in the build/linking process?

I guess a user wanting to compile openbabel with python bindings from source on OSX, using non-system python (like anaconda), now only has the option to manually fix library paths using `otool -L`. I wonder whether it's possible to do this during the build process. For example, if e.g. `-DPYTHON_LIBRARY` or `-DCAIRO_LIBRARY` are set, the linker could be instructed to use the provided path name instead of the install_name to link the library (maybe after checking if the install_name is valid). Alternatively, one could post-process the various libraries using `install_name_tool` to fix the path of dynamically linked objects. Clearly, the first option is more elegant.

**Comment by patrickfuller** [comment] 2015-11-25 17:21
First, all the credit for the conda binary goes to @rwest and @connie (discussion [here](https://github.com/conda/conda-recipes/pull/310)). All I did was run a more recent git commit through their build script.

There's a note [hidden on binstar](https://anaconda.org/patrickfuller/openbabel):

> Tested on Python 2 and 3, Mac and Ubuntu. Requires adding asmeurer and rwest to your ~/.condarc channels. These channels allow the installer to grab the `pkg-config` and `cairo` dependencies.

@rwest had to patch directly into openbabel's source to resolve certain dependency paths (the goal was to have *all* dependencies managed through conda). If you don't use their channels for pulling dependencies, the links are going to be incorrect.

For replication's sake, my `~/.condarc` is:

```
channels:
  - defaults
  - asmeurer
  - rwest
  - rmg
  - patrickfuller
```

The binary should work. If it doesn't, my pre-conda workflow used a whole lot of `install_name_tool` commands.

```
install_name_tool -change libpython3.4m.dylib ~/miniconda3/lib/libpython3.4m.dylib ~/miniconda3/lib/python3.4/site-packages/_openbabel.so
for l in xmlformat pubchem cmlreactformat cmlformat cdxmlformat; do install_name_tool -change libxml2.2.dylib ~/miniconda3/lib/libxml2.dylib ~/miniconda3/lib/openbabel/2.3.90/$l.so; done
```

It's a mess and really not recommended.

Let me know if this helps!

**Comment by yayahjb** [comment] 2016-02-19 16:20
At least for pdbqtformat.cpp, part of the problem seems to be a difference between clang and gcc in how clang handles a decrement of an iterator.   In clang (at least on Yosemite) a decrement of an iterator already at .begin() can produce a segfault on subsequent use, so you have to add lots of extra tests.  What I have tried so far in pdbqtformat.cpp that seems to work (at least for 4dui.pdb) at line 499 ff in pdbqtformat.cpp is

    multimap <unsigned int, unsigned int>::iterator it=how_many_atoms_move.begin();
    if ((!moves_many) && !how_many_atoms_move.empty()) {it=how_many_atoms_move.end();
        if (it!=how_many_atoms_move.begin())--it;}
    for (unsigned int i = 1; i <= depth; i++)
    {
      free_bonds.insert((*it).second);
      if (!moves_many) {if (it!=how_many_atoms_move.begin())--it;}
      else{if (it!=how_many_atoms_move.end())++it;}
    }

This would suggest are review of all cases of --it or it-- in all iterator uses to make sure they are protected for use with clang.  ALternatively one could report it as a clang bug, but I am not sure how productive that would be.
  -- H. J. Bernstein

**Comment by ghutchis** [comment] 2016-04-06 14:31
I'm going to see what I can do to provide an official conda binary package for 2.4. In the meantime, I'm closing this.

**Closed by ghutchis** 2016-04-06 14:31 UTC
