### ISSUE TITLE
CMake Error 

### ISSUE THREAD

**Issue by xqding** [openbabel/openbabel#382] opened 2017-02-21 16:03 UTC
Hello,

I'm trying to install openbabel-2.4.1 and have the following error message from make:

Linking C shared library ../../../lib/libinchi.so
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libinchi.so.0.4.1] Error 1
make[1]: *** [src/formats/libinchi/CMakeFiles/inchi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] Building CXX object src/CMakeFiles/openbabel.dir/query.o
[ 23%] [ 23%] Building CXX object src/CMakeFiles/openbabel.dir/rand.o
Building CXX object src/CMakeFiles/openbabel.dir/residue.o
[ 23%] Building CXX object src/CMakeFiles/openbabel.dir/ring.o
[ 23%] Building CXX object src/CMakeFiles/openbabel.dir/rotamer.o
[ 24%] Building CXX object src/CMakeFiles/openbabel.dir/rotor.o
[ 24%] Building CXX object src/CMakeFiles/openbabel.dir/spectrophore.o
[ 24%] Building CXX object src/CMakeFiles/openbabel.dir/tautomer.o
[ 24%] Building CXX object src/CMakeFiles/openbabel.dir/tokenst.o
[ 25%] Building CXX object src/CMakeFiles/openbabel.dir/transform.o
[ 25%] Building CXX object src/CMakeFiles/openbabel.dir/typer.o
[ 25%] Building CXX object src/CMakeFiles/openbabel.dir/obmolecformat.o
[ 26%] Building CXX object src/CMakeFiles/openbabel.dir/conformersearch.o
[ 26%] Building CXX object src/CMakeFiles/openbabel.dir/confsearch.o
[ 26%] Building CXX object src/CMakeFiles/openbabel.dir/distgeom.o
[ 26%] Building CXX object src/CMakeFiles/openbabel.dir/dlhandler_unix.o
[ 27%] Building CXX object src/CMakeFiles/openbabel.dir/depict/depict.o
[ 27%] Building CXX object src/CMakeFiles/openbabel.dir/depict/svgpainter.o
[ 27%] Building CXX object src/CMakeFiles/openbabel.dir/math/matrix3x3.o
[ 28%] [ 28%] Building CXX object src/CMakeFiles/openbabel.dir/math/spacegroup.o
Building CXX object src/CMakeFiles/openbabel.dir/math/transform3d.o
[ 28%] Building CXX object src/CMakeFiles/openbabel.dir/math/vector3.o
[ 28%] Building CXX object src/CMakeFiles/openbabel.dir/math/align.o
[ 29%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/stereo.o
[ 29%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/tetranonplanar.o
[ 29%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/tetraplanar.o
[ 29%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/squareplanar.o
[ 30%] [ 30%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/cistrans.o
Building CXX object src/CMakeFiles/openbabel.dir/stereo/tetrahedral.o
[ 30%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/perception.o
[ 31%] Building CXX object src/CMakeFiles/openbabel.dir/stereo/facade.o
Linking CXX shared library ../lib/libopenbabel.so
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libopenbabel.so.5.0.0] Error 1
make[1]: *** [src/CMakeFiles/openbabel.dir/all] Error 2
make: *** [all] Error 2

The cmake option I used is 
`cmake ../openbabel_master -DCMAKE_INSTALL_PREFIX=/home/xqding/local/ -DPYTHON_BINDINGS=ON -DEIGEN3_INCLUDE_DIR=/home/xqding/apps/Eigen3`.

Thanks,
Xinqiang

**Comment by baoilleach** [comment] 2017-02-21 16:38
Some more information needed. What OS and version? What compiler and
version? According to google, it sounds like you have lib64 versus lib
problems.

- Noel

**Comment by emprice** [comment] 2017-03-11 03:56
I'm actually having a similar problem installing. I eventually got OpenBabel to compile by hacking a Python script together that modified the `link.txt` and `relink.txt` files to link with /lib64 instead of /lib. I do have both directories in my tree, but it's never caused a problem before now. Any thoughts? I'm not great with CMake, so I may just be missing something obvious.

The OS is Linux (I think OpenSUSE?). CMake is version 2.8.12.2.

**Comment by emprice** [comment] 2017-03-11 10:45
**Update:** By manually disabling the GUI in CMakeLists.txt (why does -DBUILD_GUI=BOOL:OFF not work?) and using the command

    cmake -DCMAKE_INSTALL_PREFIX=/ -DCMAKE_SHARED_LINKER_FLAGS="-L/lib64" .

I was able to finally compile the latest version. There's an additional bug regarding a file `data/aromatic.txt`, which doesn't seem to exist, but that's an issue for a separate thread.

The problem seems to relate to libstdc++, which on my machine lives at `/lib64`. CMake doesn't realize this and never adds the path to the build command. There *is* a libstdc++ at `/lib`, but it's the wrong version, which causes the errors. This may be a useful hack for someone else with the same problem (@xqding), but it's not ideal.

**Comment by baoilleach** [comment] 2017-03-11 14:05
Just =OFF will do the trick.

But we still can't reproduce it as this end until we know the exact OS. It takes some time to download and install an OS so we need the specifics.

**Comment by emprice** [comment] 2017-03-11 14:27
Found the info you need:

    $ uname -a
    Linux sabriel 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

    $ lsb_release -a
    LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0 amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
    Distributor ID: CentOS
    Description:    CentOS release 6.8 (Final)
    Release:        6.8
    Codename:       Final

Additionally, I've been stripping my home directory, which I suppose I should add back now. So the directory with the libstdc++ I want to compile against is actually `/home/eprice/lib64`, but CMake wants to compile only against `/home/eprice/lib`.

**Comment by cowsandmilk** [comment] 2017-03-11 15:27
Is there a reason you are using a  libstdc++ in your home directory? Openbabel 2.4.1 happily links with /usr/lib64/libstdc++.so.6 using the default options on CentOS 6.8

**Comment by emprice** [comment] 2017-03-11 16:14
My org's software is pretty outdated, so I built a lot of things myself and use my home directory like a root directory. My use case may be too specialized. In any case, I eventually got it to compile using the option I described above, forcing it to add my /home/eprice/lib64 directory to the build command, so this is really not a priority issue :smile:

**Comment by baoilleach** [comment] 2017-03-11 16:57
Closing as a won't fix, unless original poster reopens.

**Closed by baoilleach** 2017-03-11 16:57 UTC
