### ISSUE TITLE
Too many open files with with pybel

### ISSUE THREAD

**Issue by EricTing** [openbabel/openbabel#250] opened 2016-01-19 16:37 UTC
I need to process large amount of SDF format files, each has multiple molecules, filter them by the total atom numbers, return the molecules as python objects. 

Below is my code:
`mols = [mol for mol in pybel.readfile(format="sdf", filename=ifn) if len(mol.atoms) >= minimum_size]`

It seems that the files are left open by `pybel.readfile` and I got errors `[Errno 24] Too many open files` after long time running.
I found a thread (http://forums.openbabel.org/Too-many-open-files-error-td957493.html) on the issue but cannot find a solution based on that.

I am wondering if the `too many open files` issues have been resolved.
Is it because my code is wrong?

**Comment by mwojcikowski** [comment] 2016-03-07 13:09
Which version of OB do you use? My first guess would be, that you have "latest" stable release. Try git master version, as I remember correctly @dkoes has fixed a memory leak in OBConversion, which was connected witch not cleaning up stuff after execution.

**Comment by EricTing** [comment] 2016-04-04 16:52
@mwojcikowski : `Open Babel 2.3.1 -- Oct 27 2015 -- 18:47:14`

**Comment by ghutchis** [comment] 2016-04-06 17:30
For one, you should use a newer version of OB. But I don't think the problem is that particular line.

As you said, you're calling *that* line inside a loop over multiple files.

You don't want to use `pybel.readfile` in a loop. (You also don't want to use the corresponding C++ idiom in a loop either, but most people in C++ use streams.) As you see, it leaves files open. It has no way of knowing when you're done reading, so it cannot free the file stream.

Handle your file reading with your python code and read from the file object. Close it when you're done.

**Comment by ghutchis** [comment] 2016-04-06 17:31
BTW, this is better handled in the mailing list than in the bug tracker. With the current API, there's no way to signal (in C++ or Pybel) to close the file.

**Closed by ghutchis** 2016-04-06 17:31 UTC
