### ISSUE TITLE
ionic aluminum trichloride gets hydrides added

### ISSUE THREAD

**Issue by jeffjanes** [openbabel/openbabel#249] opened 2016-01-18 19:25 UTC
In both 2.3.2 and in git HEAD, the ionic form of aluminum trichloride gets mangled upon smiles round-tripping.  Hydrides are added.

/usr/bin/obabel -ismi <(echo '[Al+3].[Cl-].[Cl-].[Cl-]') -ocan
[AlH3+3].[Cl-].[Cl-].[Cl-]

**Comment by ghutchis** [comment] 2016-01-29 18:57
My initial thought was "oh, this is easy.. add in an ionic [Al+3] pattern to the implicit valences"

It's a bit harder than that.. In principal, you should check to make sure there's actually enough counter ions to balance..

I'd be OK with adding a small patch to the implicit valence rules, since I suspect the impact would be small.

**Comment by jeffjanes** [comment] 2016-04-07 04:36
Aren't the square brackets around an atom supposed to prevent any implicit valences from being assumed?  Is this a divergence between Daylight SMILES and OpenBabel SMILES?

**Comment by baoilleach** [comment] 2016-04-07 20:38
It's a bug, or rather it was never implemented. I have code for
implementing the smiles valence model lying around which would fix this, at
least when reading. Let me see if I can dig it up.

- Noel

**Comment by baoilleach** [comment] 2016-04-10 20:44
Just a note. It's a little weirder than I expected.

>obabel -:"[Al+3].C" -osmi
[AlH3+3].C

but
>obabel -:"[Al+3]" -osmi
[Al+3]

Haven't had a chance to track down the cause yet.

**Comment by baoilleach** [comment] 2016-05-12 19:13
The difference is due to perceived spin multiplicity on the Al:

Al impval 3 hyb 2 fcharge 3 spinmult 0
C impval 4 hyb 3 

Al impval 3 hyb 2 fcharge 3 spinmult 4

Next step is to track down why

**Comment by baoilleach** [comment] 2016-05-12 20:27
Ok - so I think it _is_ a problem with the SMILES implicit valence. It pops up in AssignSpinMultiplicity, where OBMols with a single atom shortcircuit the function, hence the differing behaviour in the two cases.

**Comment by baoilleach** [comment] 2017-05-30 20:09
Fixed by #1576.

**Closed** 2017-06-17 14:55 UTC
Labels: in progress
