### ISSUE TITLE
maeparser linkage error?

### ISSUE THREAD

**Issue by joergkurtwegner** [openbabel/openbabel#2033] opened 2019-09-12 21:18 UTC
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: latest git clone
Operating system and version: RHEL7, latest cmake from source

## Expected Behavior
compile

## Actual Behavior
make -j2
Scanning dependencies of target maeparser
[  1%] Building CXX object external/maeparser-1.1/CMakeFiles/maeparser.dir/MaeBlock.cpp.o
[  1%] Building CXX object external/maeparser-1.1/CMakeFiles/maeparser.dir/Buffer.cpp.o
[  1%] Building CXX object external/maeparser-1.1/CMakeFiles/maeparser.dir/MaeParser.cpp.o
[  1%] Building CXX object external/maeparser-1.1/CMakeFiles/maeparser.dir/Reader.cpp.o
[  1%] Building CXX object external/maeparser-1.1/CMakeFiles/maeparser.dir/Writer.cpp.o
[  2%] Linking CXX shared library ../../lib/libmaeparser.so
/usr/local/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)':
zlib.cpp:(.text+0x13c): undefined reference to `crc32'
/usr/local/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::reset(bool, bool)':
zlib.cpp:(.text+0x1b1): undefined reference to `deflateReset'
zlib.cpp:(.text+0x1c6): undefined reference to `inflateEnd'
zlib.cpp:(.text+0x1d9): undefined reference to `inflateReset'
zlib.cpp:(.text+0x1f1): undefined reference to `deflateEnd'
/usr/local/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)':
zlib.cpp:(.text+0x510): undefined reference to `inflateInit2_'
zlib.cpp:(.text+0x543): undefined reference to `deflateInit2_'
/usr/local/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::xdeflate(int)':
zlib.cpp:(.text+0x184): undefined reference to `deflate'
/usr/local/lib/libboost_iostreams.a(zlib.o): In function `boost::iostreams::detail::zlib_base::xinflate(int)':
zlib.cpp:(.text+0x194): undefined reference to `inflate'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libmaeparser.so.1.1] Error 1
make[1]: *** [external/maeparser-1.1/CMakeFiles/maeparser.dir/all] Error 2
make: *** [all] Error 2

**Comment by lorton** [comment] 2019-09-14 17:25
I'm pretty sure this is just an error with not including `-lz` for some reason.  Could you run:
`make -j2 VERBOSE=1` instead of just `make -j2`?

**Comment by lorton** [comment] 2019-09-14 17:25
@ghutchis - feel free to assign this to me

**Comment by ghutchis** [comment] 2019-09-14 19:13
Yes, it looks like a link issue.

**Comment by lorton** [comment] 2019-09-15 20:34
Just a note @joergkurtwegner that you should be able to build it turning WITH_MAEPARSER=off to work around this until we get a fix in.

**Comment by ricrogz** [comment] 2019-10-15 21:17
@joergkurtwegner I just had a quick look at your report, do you still have this problem? Have you tried with a more recent version of maeparser?

From what I see, you are linking against a boost instance under /usr/local/ ... did you build it yourself? is it possible that it has support for zlib disabled? I have seen similar messages on Win builds that did not have zlib support in boost.

**Comment by baoilleach** [comment] 2019-10-16 11:01
It's a bug (nothing should break the build), but without further feedback or the ability to reproduce, we'll have to mark as closed for now.

**Closed** 2019-10-25 14:54 UTC
Labels: works for me
