### ISSUE TITLE
Non usual resnames when converting from SDF to PDB

### ISSUE THREAD

**Issue by hmarlo** [openbabel/openbabel#1767] opened 2018-01-29 14:18 UTC
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 2.4.1 -- Nov 22 2017 -- 15:48:24
Operating system and version: Linux hostname 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Expected Behavior

I expect the molecule to have the correct resname (UNL by default) in the output PDB file.

## Actual Behavior

```
obabel -p 7.4 -i sdf Spongothymidine_1.sdf -o pdb
```

My output
```
ATOM      1  C5M   T A   1      26.362  58.646  91.209  1.00  0.00           C  
ATOM      2  C5    T A   1      25.922  57.822  90.045  1.00  0.00           C  
ATOM      3  C6    T A   1      24.699  57.300  89.909  1.00  0.00           C  
ATOM      4  N1    T A   1      24.311  56.600  88.785  1.00  0.00           N  
ATOM      5  C1*   T A   1      22.945  56.099  88.619  1.00  0.00           C  
ATOM      6  O4*   T A   1      22.049  56.831  89.499  1.00  0.00           O  
ATOM      7  C4*   T A   1      21.402  55.880  90.357  1.00  0.00           C  
ATOM      8  C5*   T A   1      21.209  56.431  91.767  1.00  0.00           C  
ATOM      9  O5*   T A   1      20.616  55.451  92.611  1.00  0.00           O  
ATOM     10  C3*   T A   1      22.230  54.602  90.335  1.00  0.00           C  
ATOM     11  O3*   T A   1      21.417  53.477  90.642  1.00  0.00           O  
ATOM     12  C2*   T A   1      22.722  54.594  88.897  1.00  0.00           C  
ATOM     13  O2*   T A   1      23.810  53.710  88.674  1.00  0.00           O  
ATOM     14  C2    T A   1      25.178  56.411  87.710  1.00  0.00           C  
ATOM     15  O2    T A   1      24.855  55.835  86.676  1.00  0.00           O  
ATOM     16  N3    T A   1      26.440  56.923  87.867  1.00  0.00           N  
ATOM     17  C4    T A   1      26.905  57.582  88.965  1.00  0.00           C  
ATOM     18  O4    T A   1      28.052  58.001  89.073  1.00  0.00           O  
ATOM     19 H5M1   T A   1      25.556  58.736  91.907  1.00  0.00           H  
ATOM     20 H5M2   T A   1      26.650  59.618  90.868  1.00  0.00           H  
ATOM     21 H5M3   T A   1      27.195  58.173  91.685  1.00  0.00           H  
ATOM     22  H6    T A   1      24.018  57.426  90.674  1.00  0.00           H  
ATOM     23  H1*   T A   1      22.745  56.246  87.578  1.00  0.00           H  
ATOM     24  H4*   T A   1      20.415  55.669  90.003  1.00  0.00           H  
ATOM     25 H5*1   T A   1      20.573  57.291  91.724  1.00  0.00           H  
ATOM     26 H5*2   T A   1      22.165  56.699  92.167  1.00  0.00           H  
ATOM     27  H5*   T A   1      19.748  55.201  92.256  1.00  0.00           H  
ATOM     28  H3*   T A   1      23.023  54.560  91.052  1.00  0.00           H  
ATOM     29  H3*   T A   1      20.666  53.444  90.029  1.00  0.00           H  
ATOM     30  H2*   T A   1      22.038  54.179  88.186  1.00  0.00           H  
ATOM     31  H2*   T A   1      24.546  53.950  89.258  1.00  0.00           H  
ATOM     32  H3    T A   1      27.067  56.804  87.118  1.00  0.00           H  
```

The file:
[Spongothymidine.txt](https://github.com/openbabel/openbabel/files/1673827/Spongothymidine.txt)

Why is that happening? I am missing something?

Thank you! :D

**Comment by baoilleach** [comment] 2018-03-18 13:13
I think this is the expected behaviour. We detect amino acid monomers and apparently nucleic acids too. These are PDB atom names. If you'd like us to add an option to force "UNL", that could be done though.

**Comment by baoilleach** [comment] 2018-04-12 12:14
Closing since no comment from OP. Feel free to reopen if necessary.

**Closed by baoilleach** 2018-04-12 12:14 UTC

**Comment by hmarlo** [comment] 2018-04-12 16:38
Hey! Sorry! I forgot about it. No problem, we can live with it, we probably will change the naming and done.

Sorry for bothering.
