### ISSUE TITLE
Python3.6 openbabel: No module named 'DLFCN'

### ISSUE THREAD

**Issue by klniu** [openbabel/openbabel#368] opened 2017-01-09 03:18 UTC
In the new release Python 3.6, the DLFCN is removed, see https://docs.python.org/3.6/whatsnew/3.6.html

```
File "/usr/lib/python3.6/site-packages/openbabel.py", line 6, in <module>
    import DLFCN as dl
ModuleNotFoundError: No module named 'DLFCN'
```

**Comment by mwojcikowski** [comment] 2017-02-06 09:08
Two questions:

1. Is it cross-platform compatible?
2. Is it backward compatible?

**Comment by baoilleach** [comment] 2017-02-06 13:12
I would be open to just putting the constant in there directly. After all, there's no need to import the whole of ctypes just for the number '4' or whatever.

**Comment by cowsandmilk** [comment] 2017-02-06 13:52
Isn't the point that the value is different on different platforms?

For instance, on my mac, it is 8. On my ubuntu system, it is 256.

**Comment by baoilleach** [comment] 2017-02-06 13:56
That would be a problem alright. Ignore my prevoius comment so.

Ultimately the issue is that on some platforms, the DL loader fails to load the plugins without this kludge. This is also the case for other bindings and I think the correct solution is to move towards statically including the plugins in the main .so, so to avoid this issue completely.

**Comment by mwojcikowski** [comment] 2017-02-06 15:07
Also the problem with `RTLD_GLOBAL` is that it messes up some other Python libraries which do not anticipate `RTLD_GLOBAL`. Prime example is L-BFGS-B from scipy which segfaults when loaded after OB.

**Comment by baoilleach** [comment] 2017-02-06 15:16
That's right. But it's only needed for plug-in load, and can be turned off afterwards. Maybe the bindings should instantiate an OBConversion object to force plugin loading, and then turn it off.

**Comment by mwojcikowski** [comment] 2017-02-06 15:52
I can confirm that calling following code after importing openbabel and/or pybel "unbreaks" other C libraries:

> ob.OBConversion()
> sys.setdlopenflags(sys.getdlopenflags() ^ RTLD_GLOBAL)

Pybel does initialize OBConversion(), I repeated it just to be sure (not all may want to use friendly interface).

**Comment by hseara** [comment] 2017-08-23 07:15
Shall we close this bug after the merge? If further cleaning wants to be done, it can be done aside. It is pleasant to keep the bug/tracker clean.

**Comment by baoilleach** [comment] 2018-02-10 13:43
Yes - this should have been closed after the merge.

**Closed by baoilleach** 2018-02-10 13:43 UTC
