### ISSUE TITLE
SMARTS does not match itself

### ISSUE THREAD

**Issue by n-yoshikawa** [openbabel/openbabel#2025] opened 2019-09-03 15:12 UTC
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Ubuntu 18.04

`OBSmartsPattern` does not match itself for some SMARTS.
The simplest example was `[c]1ccc[c]c1`.

```
$ echo '[c]1ccc[c]c1' | obgrep -c '[c]1ccc[c]c1'
0
```

I know there are limitations in the current implementation ([Wiki](https://openbabel.org/wiki/SMARTS)), but this does not seem to be reported.

**Comment by baoilleach** [comment] 2019-09-03 19:19
It's not a bug. obgrep is looking for six aromatic carbons in a ring. But the original molecule is not aromatic according to the Daylight aromaticity, which unfortunately does not include contributions of radicals to the 4n+2 count. In other words, the original molecule is interpreted as "[C]1=C[C]=CC=C1", and so doesn't match.

Closing this issue, but feel free to reopen if unclear or you think I've misunderstood.

**Closed by baoilleach** 2019-09-03 19:19 UTC
