### ISSUE TITLE
Open Babel on fedora 30

### ISSUE THREAD

**Issue by Vcald** [openbabel/openbabel#1984] opened 2019-05-11 08:22 UTC
I have a failure when trying to compile Open Babel 2.4.1 on fedora 30 x64.
I configure with this command from the created build directory:
cmake -DRUN_SWIG=yes -DPYTHON_BINDINGS=yes -DBUILD_GUI=yes ..
Then run make -j4
Then it fails like this:
[ 20%] Building CXX object src/CMakeFiles/plugin_forcefields.dir/forcefields/forcefieldgaff.o
[ 21%] Building CXX object src/CMakeFiles/plugin_forcefields.dir/forcefields/forcefieldghemical.o
[ 21%] Building CXX object src/CMakeFiles/plugin_forcefields.dir/forcefields/forcefieldmmff94.o
[ 21%] Building CXX object src/CMakeFiles/plugin_forcefields.dir/forcefields/forcefielduff.o
[ 21%] Linking CXX shared module ../lib/plugin_forcefields.so
/usr/bin/ld: CMakeFiles/plugin_forcefields.dir/forcefields/forcefieldmmff94.o(.debug_loc+0x800000001262df): reloc against `.text._ZN9OpenBabel12OBForceFieldD0Ev': error 4
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/plugin_forcefields.dir/build.make:134: lib/plugin_forcefields.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1159: src/CMakeFiles/plugin_forcefields.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Any hint?

**Comment by baoilleach** [comment] 2019-05-11 09:25
Are you using the gcc that came with the OS? What is the output of gcc -v?
It looks like a position independent code problem but I've never seen it
happen with a system compiler. Maybe @rathann can comment.

**Comment by Vcald** [comment] 2019-05-11 10:12
Yes...I am using the native gcc...the version is 9.1.1
But what is weird is this: if I delete the openbabel folder...reboot the pc...and redo the same thing...I get a failure at a different point on a different file and percentage...
I have no idea of what is going on.
Any hint?

**Comment by Vcald** [comment] 2019-05-11 12:01
I have also tried with the github version...this is what I get using the very same approach:
[ 68%] Built target fhformat
[ 68%] Building CXX object src/formats/CMakeFiles/painterformat.dir/__/depict/commandpainter.cpp.o
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o: in function `OpenBabel::XTCFormat::xdropen(__rpc_xdr*, char const*, char const*)':
xtcformat.cpp:(.text+0xd4): undefined reference to `xdrstdio_create'
/usr/bin/ld: xtcformat.cpp:(.text+0x11a): undefined reference to `xdrstdio_create'
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o: in function `OpenBabel::XTCFormat::xdr3dfcoord(__rpc_xdr*, float*, int*, float*)':
xtcformat.cpp:(.text+0x856): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x8b2): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x919): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x929): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x939): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x949): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x959): undefined reference to `xdr_int'
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o:xtcformat.cpp:(.text+0x969): more undefined references to `xdr_int' follow
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o: in function `OpenBabel::XTCFormat::xdr3dfcoord(__rpc_xdr*, float*, int*, float*)':
xtcformat.cpp:(.text+0xa77): undefined reference to `xdr_opaque'
/usr/bin/ld: xtcformat.cpp:(.text+0xcf9): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0xd14): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0xd27): undefined reference to `xdr_vector'
/usr/bin/ld: xtcformat.cpp:(.text+0xd33): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0xd46): undefined reference to `xdr_vector'
/usr/bin/ld: xtcformat.cpp:(.text+0xd5e): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x10ab): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x10bb): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x10cb): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x10db): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x10eb): undefined reference to `xdr_int'
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o:xtcformat.cpp:(.text+0x10fb): more undefined references to `xdr_int' follow
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o: in function `OpenBabel::XTCFormat::xdr3dfcoord(__rpc_xdr*, float*, int*, float*)':
xtcformat.cpp:(.text+0x1aba): undefined reference to `xdr_opaque'
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o: in function `OpenBabel::XTCFormat::ReadMolecule(OpenBabel::OBBase*, OpenBabel::OBConversion*)':
xtcformat.cpp:(.text+0x1d17): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d30): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d54): undefined reference to `xdr_int'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d64): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d74): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d84): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x1d94): undefined reference to `xdr_float'
/usr/bin/ld: xtcformat.cpp:(.text+0x1da4): undefined reference to `xdr_float'
/usr/bin/ld: CMakeFiles/xtcformat.dir/xtcformat.cpp.o:xtcformat.cpp:(.text+0x1db4): more undefined references to `xdr_float' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/formats/CMakeFiles/xtcformat.dir/build.make:92: lib/xtcformat.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:5102: src/formats/CMakeFiles/xtcformat.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Linking CXX shared module ../../lib/gamessukformat.so
[ 68%] Built target gamessukformat
[ 68%] Linking CXX shared module ../../lib/painterformat.so
[ 68%] Built target painterformat
make: *** [Makefile:141: all] Error 2

**Comment by ghutchis** [comment] 2020-05-07 18:15
I'm closing - this seems like a duplicate of #1996

**Closed by ghutchis** 2020-05-07 18:15 UTC
