### ISSUE TITLE
Reporting installation bug with Csharp binding.

### ISSUE THREAD

**Issue by cyclone923** [openbabel/openbabel#1867] opened 2018-07-12 22:14 UTC
Hi,

I am having a bug installing openbabel with c# bindings.
I have included needed information in the attached files.
[cmake.info.txt](https://github.com/openbabel/openbabel/files/2190492/cmake.info.txt)
[hardware.info.txt](https://github.com/openbabel/openbabel/files/2190493/hardware.info.txt)
[make.info.txt](https://github.com/openbabel/openbabel/files/2190494/make.info.txt)
[mcs.info.txt](https://github.com/openbabel/openbabel/files/2190495/mcs.info.txt)
[software.info.txt](https://github.com/openbabel/openbabel/files/2190496/software.info.txt)

At the end of the make step, it has errors like this:

./VectorBond.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorDouble.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorInt.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorMol.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorOBExternalBond.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorOBVector3.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorResidue.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorRing.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorString.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorTorsion.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorUInt.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorUShort.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorVecDouble.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorVecInt.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorVecOBVector3.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorVecUInt.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpAtom.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpBond.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpData.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpInternalCoord.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpRing.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
./VectorpRotor.cs(47,23): error CS0246: The type or namespace name Action' could not be found. Are you missingSystem' using directive?
Compilation failed: 22 error(s), 0 warnings
[100%] Building CXX object test/CMakeFiles/test_runner.dir/obtest.cpp.o
make[2]: *** [/Users/chengxiyang/Downloads/openbabel-master/scripts/csharp/openbabel-csharp.cpp] Error 1
make[2]: *** Deleting file `/Users/chengxiyang/Downloads/openbabel-master/scripts/csharp/openbabel-csharp.cpp'
make[1]: *** [scripts/CMakeFiles/bindings_csharp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../bin/test_runner
[100%] Built target test_runner
make: *** [all] Error 2

The code I used is from the Github-master.
You can contact me at yangchen@oregonstate.edu.
Thanks for help!

**Comment by ghutchis** [comment] 2020-05-07 18:28
This is a duplicate of #1857

**Closed by ghutchis** 2020-05-07 18:28 UTC
