### ISSUE TITLE
Problem when computing multiple fingerprints using ECFP4

### ISSUE THREAD

**Issue by hmenager** [openbabel/openbabel#1886] opened 2018-09-10 19:54 UTC
- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 2.4.1
Operating system and version: Ubuntu 18.04.1 LTS or CentOS 7
For ubuntu:
```shell
$ obabel -V
Open Babel 2.4.1 -- Jul 25 2018 -- 22:40:34
$ pip show openbabel
Name: openbabel
Version: 2.4.1
Summary: Python interface to the Open Babel chemistry library
Home-page: http://openbabel.org/
Author: Noel O'Boyle
Author-email: openbabel-discuss@lists.sourceforge.net
License: GPL
Location: [edited]
Requires: 
```

## Expected Behavior

When I compute fingerprints using ECFP4, If I compute the same fingerprint for a compound many times, the result should always be identical, and the resulting tanimoto similarity = 1 for the same structure.

## Actual Behavior

If too many fingerprints are computed, the results become arbitrary: the same smile returns many different values. 

1) create the following script, which computes the fingerprint for "CCCCCCCCCC" 300 times:
```python3
import openbabel as ob
from pybel import Fingerprint

fingerprinter = ob.OBFingerprint.FindFingerprint("ECFP4")
#fingerprinter = ob.OBFingerprint.FindFingerprint("FP4")
smiles_parser = ob.OBConversion()
smiles_parser.SetInFormat("smi")

def fp(smiles):
    """
    compute and return the fingerprint from a SMILES
    """
    mol = ob.OBMol()
    smiles_parser.ReadString(mol, smiles)
    fp = ob.vectorUnsignedInt()
    fingerprinter.GetFingerprint(mol, fp)
    return fp

for entry in ["C"*10] *300:
    print(Fingerprint(fp(entry)).bits)
```
2) run it to count the number of different results:
```shell
python test_ob_ecfp4.py | sort | uniq | wc -l
# result for me is 18
```

Please note that:
- if we use e.g. FP4 (or others) the results are always reliable
- if the list is small enough (more or less between 5 and 10?) the result is always the same and becomes reliable somehow

Please let me know if you need additional details. I can contribute a python test if needed.

**Comment by fredrikw** [comment] 2018-09-11 06:35
I could not reproduce on Windows10 running OpenBabel 2.4.1, if that helps in locating the issue...

**Comment by hmenager** [comment] 2018-09-11 07:19
thank you @fredrikw for your help. Does this mean that if you run `python test_ob_ecfp4.py | sort | uniq | wc -l` you get `1` as a result?

**Comment by baoilleach** [comment] 2018-09-11 09:58
I believe that the problem you are describing was fixed in the development version. See https://github.com/openbabel/openbabel/pull/1829. I recommend you use the development version as this was not the only fix to ECFP. I'm going to mark as closed, but feel free to reopen if neccessary.

**Closed by baoilleach** 2018-09-11 09:58 UTC
