### ISSUE TITLE
MOL file bug

### ISSUE THREAD

**Issue by ignaspakamore** [openbabel/openbabel#2550] opened 2022-11-21 09:48 UTC
For large molecules and crystals, the numbers of atoms and bonds are not separated by space (144168  0  0  0  0  0  0  0  0999 V2000 --> 144 168  0  0  0  0  0  0  0  0999 V2000). The same is for bonds ( 34137  1  0  0  0  0 -->  34 137  1  0  0  0  0). I believe this happens when more than 100 atoms are present in the structure. 

```
 OpenBabel11212209413D

144168  0  0  0  0  0  0  0  0999 V2000
    3.7578    1.5662    5.9493 Si  0  0  1  0  0  0  0  0  0  0  0  0
    3.1670    0.0000    5.7629 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    2.4831    5.4923 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.2733   13.4648    5.9493 Si  0  0  2  0  0  3  0  0  0  0  0  0
   11.8640    0.0000    5.7629 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479   12.5479    5.4923 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.2733    1.5662    9.0817 Si  0  0  1  0  0  0  0  0  0  0  0  0
   11.8640    0.0000    9.2681 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    2.4831    9.5387 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.7578   13.4648    9.0817 Si  0  0  2  0  0  3  0  0  0  0  0  0
    3.1670    0.0000    9.2681 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831   12.5479    9.5387 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9493    3.7578    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
    5.7629    3.1670    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    5.4923    2.4831    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9493   11.2733   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
    5.7629   11.8640    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    5.4923   12.5479   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.0817   11.2733    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
    9.2681   11.8640    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    9.5387   12.5479    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.0817    3.7578   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
    9.2681    3.1670    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    9.5387    2.4831   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5662    5.9493    3.7578 Si  0  0  1  0  0  0  0  0  0  0  0  0
    0.0000    5.7629    3.1670 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    5.4923    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4648    5.9493   11.2733 Si  0  0  2  0  0  3  0  0  0  0  0  0
    0.0000    5.7629   11.8640 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    5.4923   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5662    9.0817   11.2733 Si  0  0  1  0  0  0  0  0  0  0  0  0
    0.0000    9.2681   11.8640 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    9.5387   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4648    9.0817    3.7578 Si  0  0  2  0  0  3  0  0  0  0  0  0
    0.0000    9.2681    3.1670 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    9.5387    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5662    3.7578    9.0817 Si  0  0  1  0  0  0  0  0  0  0  0  0
    0.0000    3.1670    9.2681 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    2.4831    9.5387 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4648   11.2733    9.0817 Si  0  0  2  0  0  3  0  0  0  0  0  0
    0.0000   11.8640    9.2681 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479   12.5479    9.5387 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5662   11.2733    5.9493 Si  0  0  1  0  0  0  0  0  0  0  0  0
    0.0000   11.8640    5.7629 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831   12.5479    5.4923 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.4648    3.7578    5.9493 Si  0  0  2  0  0  3  0  0  0  0  0  0
    0.0000    3.1670    5.7629 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    2.4831    5.4923 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.7578    5.9493   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
    3.1670    5.7629    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    5.4923   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.2733    5.9493    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
   11.8640    5.7629    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    5.4923    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.2733    9.0817   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
   11.8640    9.2681    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
   12.5479    9.5387   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.7578    9.0817    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
    3.1670    9.2681    0.0000 O   0  0  0  0  0  1  0  0  0  0  0  0
    2.4831    9.5387    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9493    1.5662   11.2733 Si  0  0  1  0  0  0  0  0  0  0  0  0
    5.7629    0.0000   11.8640 O   0  0  0  0  0  1  0  0  0  0  0  0
    5.4923    2.4831   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.9493   13.4648    3.7578 Si  0  0  2  0  0  3  0  0  0  0  0  0
    5.7629    0.0000    3.1670 O   0  0  0  0  0  1  0  0  0  0  0  0
    5.4923   12.5479    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.0817    1.5662    3.7578 Si  0  0  1  0  0  0  0  0  0  0  0  0
    9.2681    0.0000    3.1670 O   0  0  0  0  0  1  0  0  0  0  0  0
    9.5387    2.4831    2.4831 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.0817   13.4648   11.2733 Si  0  0  2  0  0  3  0  0  0  0  0  0
    9.2681    0.0000   11.8640 O   0  0  0  0  0  1  0  0  0  0  0  0
    9.5387   12.5479   12.5479 O   0  0  0  0  0  0  0  0  0  0  0  0
   11.2733   13.4648    9.0817 Si  0  0  2  0  0  3  0  0  0  0  0  0
    3.7578    1.5662    9.0817 Si  0  0  1  0  0  0  0  0  0  0  0  0
    3.7578   13.4648    5.9493 Si  0  0  2  0  0  3  0  0  0  0  0  0
   11.2733    1.5662    5.9493 Si  0  0  1  0  0  0  0  0  0  0  0  0
    9.0817   11.2733   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
    9.0817    3.7578    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
    5.9493    3.7578   13.4648 Si  0  0  2  0  0  3  0  0  0  0  0  0
    5.9493   11.2733    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
   13.4648    9.0817   11.2733 Si  0  0  2  0  0  3  0  0  0  0  0  0
    1.5662    9.0817    3.7578 Si  0  0  1  0  0  0  0  0  0  0  0  0
   13.4648    5.9493    3.7578 Si  0  0  2  0  0  3  0  0  0  0  0  0
    1.5662    5.9493   11.2733 Si  0  0  1  0  0  0  0  0  0  0  0  0
   13.4648   11.2733    5.9493 Si  0  0  1  0  0  3  0  0  0  0  0  0
    1.5662    3.7578    5.9493 Si  0  0  1  0  0  0  0  0  0  0  0  0
   13.4648    3.7578    9.0817 Si  0  0  1  0  0  3  0  0  0  0  0  0
    1.5662   11.2733    9.0817 Si  0  0  1  0  0  0  0  0  0  0  0  0
   11.2733    9.0817    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
    3.7578    9.0817   13.4648 Si  0  0  1  0  0  3  0  0  0  0  0  0
    3.7578    5.9493    1.5662 Si  0  0  1  0  0  0  0  0  0  0  0  0
   11.2733    5.9493   13.4648 Si  0  0  1  0  0  3  0  0  0  0  0  0
    9.0817   13.4648    3.7578 Si  0  0  1  0  0  3  0  0  0  0  0  0
    9.0817    1.5662   11.2733 Si  0  0  1  0  0  0  0  0  0  0  0  0
    5.9493   13.4648   11.2733 Si  0  0  1  0  0  3  0  0  0  0  0  0
    5.9493    1.5662    3.7578 Si  0  0  1  0  0  0  0  0  0  0  0  0
   10.6825    7.5155   13.2784 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    9.9986   13.0078 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3485    7.5155   13.2784 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    5.0324   13.0078 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3485    7.5155    1.7526 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    9.9986    2.0232 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.6825    7.5155    1.7526 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    5.0324    2.0232 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.2784   10.6825    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.0078    9.9986    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.2784    4.3485    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.0078    5.0324    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7526    4.3485    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0232    5.0324    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7526   10.6825    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0232    9.9986    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155   13.2784   10.6825 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986   13.0078    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155   13.2784    4.3485 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324   13.0078    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155    1.7526    4.3485 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    2.0232    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155    1.7526   10.6825 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    2.0232    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155   10.6825    1.7526 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    9.9986    2.0232 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155    4.3485    1.7526 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    5.0324    2.0232 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155    4.3485   13.2784 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    5.0324   13.0078 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.5155   10.6825   13.2784 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    9.9986   13.0078 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.6825   13.2784    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986   13.0078    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3485   13.2784    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324   13.0078    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    4.3485    1.7526    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    5.0324    2.0232    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
   10.6825    1.7526    7.5155 O   0  0  0  0  0  0  0  0  0  0  0  0
    9.9986    2.0232    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.2784    7.5155    4.3485 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.0078    9.9986    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.2784    7.5155   10.6825 O   0  0  0  0  0  0  0  0  0  0  0  0
   13.0078    5.0324    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7526    7.5155   10.6825 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0232    9.9986    9.9986 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7526    7.5155    4.3485 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0232    5.0324    5.0324 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  6  0  0  0
  1133  1  0  0  0  0
  3  1  1  0  0  0  0
  3 86  1  0  0  0  0
  4130  1  6  0  0  0
  4129  1  0  0  0  0
  6  4  1  0  0  0  0
  6 85  1  0  0  0  0
  7  8  1  1  0  0  0
  7  9  1  0  0  0  0
  7136  1  0  0  0  0
 10131  1  6  0  0  0
 10 12  1  0  0  0  0
 10132  1  0  0  0  0
 13 14  1  6  0  0  0
 13123  1  0  0  0  0
 13124  1  0  0  0  0
 13 15  1  0  0  0  0
 15 96  1  0  0  0  0
 16 18  1  6  0  0  0
 19 20  1  6  0  0  0
 19121  1  0  0  0  0
 19122  1  0  0  0  0
 19 21  1  0  0  0  0
 22 24  1  6  0  0  0
 25 26  1  6  0  0  0
 25143  1  0  0  0  0
 25144  1  0  0  0  0
 27 25  1  0  0  0  0
 28140  1  6  0  0  0
 28 30  1  0  0  0  0
 31 32  1  1  0  0  0
 31 33  1  0  0  0  0
 34 36  1  6  0  0  0
 34137  1  0  0  0  0
 34138  1  0  0  0  0
 37 38  1  1  0  0  0
 37 39  1  0  0  0  0
 37110  1  0  0  0  0
 40105  1  6  0  0  0
 40 42  1  0  0  0  0
 40106  1  0  0  0  0
 43 44  1  6  0  0  0
 43111  1  0  0  0  0
 45 43  1  0  0  0  0
 45 75  1  0  0  0  0
 46108  1  6  0  0  0
 46107  1  0  0  0  0
 48 46  1  0  0  0  0
 48 76  1  0  0  0  0
 49 51  1  6  0  0  0
 52 53  1  6  0  0  0
 52103  1  0  0  0  0
 52104  1  0  0  0  0
 52 54  1  0  0  0  0
 55 57  1  6  0  0  0
 58 59  1  6  0  0  0
 58101  1  0  0  0  0
 58102  1  0  0  0  0
 58 60  1  0  0  0  0
 60 82  1  0  0  0  0
 61 62  1  1  0  0  0
 61 63  1  0  0  0  0
 64 66  1  6  0  0  0
 64115  1  0  0  0  0
 64116  1  0  0  0  0
 67 68  1  6  0  0  0
 67117  1  0  0  0  0
 67118  1  0  0  0  0
 69 67  1  0  0  0  0
 70114  1  6  0  0  0
 70 72  1  0  0  0  0
 73129  1  6  0  0  0
 73 42  1  0  0  0  0
 73114  1  0  0  0  0
 74 11  1  1  0  0  0
 74 39  1  0  0  0  0
 74120  1  0  0  0  0
 75116  1  6  0  0  0
 75131  1  0  0  0  0
 76  5  1  6  0  0  0
 76135  1  0  0  0  0
 77 72  1  6  0  0  0
 78 23  1  6  0  0  0
 78123  1  0  0  0  0
 78104  1  0  0  0  0
 78 69  1  0  0  0  0
 79 63  1  6  0  0  0
 80 17  1  6  0  0  0
 80121  1  0  0  0  0
 80102  1  0  0  0  0
 80 66  1  0  0  0  0
 81106  1  6  0  0  0
 81 57  1  0  0  0  0
 82 35  1  6  0  0  0
 82143  1  0  0  0  0
 82112  1  0  0  0  0
 83 54  1  6  0  0  0
 83137  1  0  0  0  0
 83108  1  0  0  0  0
 84 29  1  1  0  0  0
 84 51  1  0  0  0  0
 85138  1  6  0  0  0
 85105  1  0  0  0  0
 86 47  1  6  0  0  0
 86109  1  0  0  0  0
 87107  1  6  0  0  0
 87  9  1  0  0  0  0
 87140  1  0  0  0  0
 88 41  1  1  0  0  0
 88 12  1  0  0  0  0
 88142  1  0  0  0  0
 89 56  1  6  0  0  0
 89103  1  0  0  0  0
 89122  1  0  0  0  0
 89 36  1  0  0  0  0
 90 33  1  6  0  0  0
 91 50  1  6  0  0  0
 91101  1  0  0  0  0
 91124  1  0  0  0  0
 91 27  1  0  0  0  0
 92 30  1  6  0  0  0
 93 21  1  6  0  0  0
 93115  1  0  0  0  0
 93130  1  0  0  0  0
 94 71  1  1  0  0  0
 94 24  1  0  0  0  0
 95132  1  6  0  0  0
 95 18  1  0  0  0  0
 96 65  1  6  0  0  0
 96117  1  0  0  0  0
 96134  1  0  0  0  0
 97 55  1  0  0  0  0
 97 92  1  0  0  0  0
 98 55  1  0  0  0  0
 98 77  1  0  0  0  0
 99 90  1  0  0  0  0
 99 49  1  0  0  0  0
100 79  1  0  0  0  0
100 49  1  0  0  0  0
109 37  1  0  0  0  0
110 84  1  0  0  0  0
111 88  1  0  0  0  0
112 43  1  0  0  0  0
113 95  1  0  0  0  0
113 70  1  0  0  0  0
118 76  1  0  0  0  0
119 94  1  0  0  0  0
119 61  1  0  0  0  0
120 61  1  0  0  0  0
125 22  1  0  0  0  0
125 79  1  0  0  0  0
126 22  1  0  0  0  0
126 92  1  0  0  0  0
127 77  1  0  0  0  0
127 16  1  0  0  0  0
128 90  1  0  0  0  0
128 16  1  0  0  0  0
133 74  1  0  0  0  0
134  1  1  0  0  0  0
135  7  1  0  0  0  0
136 94  1  0  0  0  0
139 81  1  0  0  0  0
139 28  1  0  0  0  0
141 31  1  0  0  0  0
141 84  1  0  0  0  0
142 31  1  0  0  0  0
144 86  1  0  0  0  0
M  END

```

**Comment by ignaspakamore** [comment] 2022-11-21 10:19
could I increase the max number using Python?

**Comment by fredrikw** [comment] 2022-11-21 10:36
I was a bit unclear there, since I just pasted from the spec (can be found at http://www.mdli.com/downloads/literature/ctfile.pdf ATM). I don't think the max of 255 is applicable for OpenBabel.
Everything is possible in Python, so you could do what you want with the text there, but why would you like to prepare a non-compliant mol-file? What is your use case?

**Comment by ghutchis** [comment] 2022-11-21 15:08
If you want more atoms and bonds, you need to use V3000 MDL format.

**Comment by ignaspakamore** [comment] 2022-11-21 16:58
@ghutchis Thanks for your recommendation! How could I set it in python code? 
My code so far is: 

```
	obConversion = openbabel.OBConversion()
	obConversion.SetInAndOutFormats("xyz", "mol")

	mol = openbabel.OBMol()

	obConversion.ReadString(mol, xyz)
	outMDL = obConversion.WriteString(mol)
        obConversion.WriteFile(mol, 'out.mol')
```

**Comment by ghutchis** [comment] 2022-11-21 17:03
Yes, Open Babel will switch to export v3000 mol files by default if there are too many atoms / bonds.

**Comment by ignaspakamore** [comment] 2022-11-21 17:09
@ghutchis I see, the issue is that it doesn't seem to do so. I work with structures that have >90 atoms and it always generates V2000-type files that do not have correct spacing between numbers.

**Comment by ghutchis** [comment] 2022-11-21 17:59
I think you misunderstand. As @fredrikw indicated above, the format specifies three characters for atoms and three characters for bonds. If you have >99 atoms or >99 bonds, there are no spaces, as per the spec.

I'm closing this. It's not a bug. OB is adhering to the spec.

**Closed by ghutchis** 2022-11-21 17:59 UTC

**Comment by nbehrnd** [comment] 2022-11-22 07:49
@ignaspakamore Let me add two additional points; both are more comment-like:
+ If you would like to have a recent compilation of the rules around .mol/.sdf (v3000) and elder .mol/.sdf(v2000), there is an archived .pdf of Biovia's documentation on [archive.org](https://web.archive.org/web/20210219065450/https://discover.3ds.com/sites/default/files/2020-08/biovia_ctfileformats_2020.pdf).  As far as I know, this is the most recent edition (August 2020)

+ As you mention crystal structures, on one hand, and mol files on the other, maybe the compiled set by [COD](http://www.crystallography.net/cod/index.php), named [cod-tools](https://wiki.crystallography.net/cod-tools/) is helpful for you.  It includes `codcif2sdf`, an utility for the CLI to bring the .cif's structure model to the .mol/.sdf format.  Often, if the cif2mol conversion by openbabel fails (e.g., "completion" of the structure based on the asymmetric unit), this one still finds a reasonable solution, especially for structure models of small organic molecules.  Though conceived for the COD repository, thanks to the .cif standard, it equally processes .cif from other sources (publications' SI, CCDC from webCSD and conquest, etc.) Depending on the operating system, the collection equally may be available as a package easier to install, too ([example Debian](https://tracker.debian.org/pkg/cod-tools)).

   Though the tool (still) writes .sdf in the v2000 format, according to COD's maintainers, a new program is under construction which eventually is going to replace `codcif2sdf`.  It were plausible that this one then will write .sdf (v3000).
