### ISSUE TITLE
gen3D plugin fails to render smiles for cholesterol

### ISSUE THREAD

**Issue by yurivict** [openbabel/openbabel#1933] opened 2019-02-24 08:45 UTC
SMILES:
```
C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)C
```

Errors/Warnings:
```
*** Open Babel Warning  in CorrectStereoAtoms
  Could not correct 4 stereocenter(s) in this molecule ()
  with Atom Ids as follows: 13 15 18 20
Warning: Stereochemistry is wrong, using the distance geometry method instead
```

The output xyz file contains only zeros for coordinates.

**Comment by n-yoshikawa** [comment] 2019-02-25 08:27
Thank you for your report. We are actively updating gen3D feature now, so failure reports are really appreciated.

I reproduced this problem in Open Babel 2.4.1, but it seem to be resolved in the current master `cfd7846`. Could you update and check again?

**Comment by pbecherer** [comment] 2019-06-11 13:35
With the latest master (commit 528f73f) I'm getting the same warning message. It sometimes refers to different stereocenters, but the behavior is essentially the same, leading to coordinates that are all zero:

~~~~
*** Open Babel Warning  in OpenBabel::OBBuilder::CorrectStereoAtoms
  Could not correct 2 stereocenter(s) in this molecule ()
  with Atom Ids as follows: 11 20
Warning: Stereochemistry is wrong, using the distance geometry method instead
~~~~

In case it matters: I'm compiling Open Babel with Visual Studio 2017 using the Visual Studio 2015 toolset.

**Comment by e-kwsm** [comment] 2019-11-07 19:31
The issue is reproduced with Open Babel 2.4.1 provided by [Debian's apt](https://packages.debian.org/buster/openbabel), but not reproduced with f84536d804b4e2b530daf8831f264ea72a5cedf0 on Debian.

**Comment by ghutchis** [comment] 2019-11-12 04:55
Yes, I'm closing this, thanks @e-kwsm

**Closed by ghutchis** 2019-11-12 04:55 UTC
