### ISSUE TITLE
Error in cis/trans stereochemistry for seemingly correct SMILES

### ISSUE THREAD

**Issue by merkys** [openbabel/openbabel#2319] opened 2021-01-26 17:21 UTC
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1+dfsg-4 (Debian package)
Operating system and version: Debian unstable

## Expected Behavior
SMILES for [COD entry 4021153](https://www.crystallography.net/cod/4021153.html) is:
```
C(=O)(/C=C1\CN(CC/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC
```
To me this SMILES looks fine. Both double bonds with cis/trans stereochemistry are defined unambiguously.

## Actual Behavior
Open Babel emits "Error in cis/trans stereochemistry":
```
$ echo 'C(=O)(/C=C1\CN(CC/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC' | obabel -i smi -o smi
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

C(=O)(C=C1CN(C/C/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC	
1 molecule converted
```
Is there a problem with the SMILES, or with the way Open Babel perceives cis/trans stereochemistry in this descriptor?

**Comment by nbehrnd** [comment] 2021-11-12 17:31
By syntax, the SMILES string is fine.  What the SMILES string describes, however, represents a hurdle for OpenBabel.

If you paste the SMILES string into an other structure2picture converter, e.g., [CDK Depict](https://www.simolecule.com/cdkdepict/depict.html), one of the double bonds of the pyrrolidine is resolved as a double bond without explicitly assigned configuration.  For me, it looks related to observations about the isomers of 2-butene filed earlier ([here](https://github.com/openbabel/openbabel/issues/2429)).

With the information shared by you, I aimed for a replication with a pristine copy of the `.cif` from COD, which was translated into a `.sdf` with cod-tools, and submitted to OpenBabel to assign a SMILES string.

```bash
codcif2sdf ./4021153.cif > reconstruct.sdf
obabel reconstruct.sdf -osmi   
```

Not anticipated by mine, the result is not
`C(=O)(/C=C1\CN(CC/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC`
but
`C(=O)(/C=C/1\CN(C\C1=C/c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC`
In other words, the then other double bond is «wavy».

While the intermediate `.sdf` follows the v2000 dialect, it may be read by e.g., by [DataWarrior](https://openmolecules.org/datawarrior/index.html)
```bash
datawarrior ./reconstruct.sdf
```
which promptly identifies both double bonds as (*Z*) configured (which indeed is .true.).  No surprise,
[cod_cif_EZ_issue.zip](https://github.com/openbabel/openbabel/files/7529354/cod_cif_EZ_issue.zip)
 CDK Depict converts SMILES string
`Cc(cc1)ccc1S(N(C/C1=C\C(OC)=O)C/C1=C\c1ccccc1)(=O)=O`
into a structure without a wavy bond.

Environment Information: OpenBabel (3.1.1+dfsf-6), Python (3.9.8), and cod-tools (3.3.0+dfsg-1) as provided in Linux Debian 12/bookworm [testing].

![CDK_depict](https://user-images.githubusercontent.com/19709084/141507918-85f9cc55-66f5-4076-a1ee-a4650613862d.png)

[cod_cif_EZ_issue.zip](https://github.com/openbabel/openbabel/files/7529359/cod_cif_EZ_issue.zip)

**Comment by baoilleach** [comment] 2021-11-12 19:16
You have two down bonds coming off atom 4. What's the origin of the Smiles
string?

**Comment by nbehrnd** [comment] 2021-11-12 21:01
@baoilleach Please give some rope here to answer your question.

The second SMILES string is (and possibly, equally the first one) assigned by OpenBabel reading the cod-tools' written `.sdf`.  Different to them, the third SMILES string was assigned by DataWarrior after import of the cod-tools' written .sdf. This kind of reading leads DataWarrior to organize each model of a `.sdf` at the beginning of a row of a matrix; indeed, there are similarities in how the data are organized to a spread sheet like gnumeric.  Then, from DataWarrior's GUI, `Chemistry` -> `From Chemical Structure` -> `Add SMILES Code` populates a new column with this content.

For clarity, may you please reformulate «You have two down bonds coming off atom 4»?  Do you refer to the third SMILES string?  Do you refer to the `.sdf` written by the cod-tools, where the fourth atom is an of oxygen bound to C [of -OMe] and C [of C=O]?  Do you identify a detail I did not consider which however should be revisited/adjusted/corrected?

**Comment by baoilleach** [comment] 2021-11-12 21:38
I was replying to the original post.

**Comment by nbehrnd** [comment] 2021-11-13 16:38
@merkys I just submitted same intermediate `reconstruct.sdf` to RDKit (currently 2020.09.5 for Debian 12/bookworm [testing]):

```python
import rdkit
from rdkit import Chem

m = Chem.MolFromMolFile("reconstruct.sdf")
print(Chem.MolToSmiles(m))
```
This assigns `COC(=O)/C=C1\CN(S(=O)(=O)c2ccc(C)cc2)C\C1=C/c1ccccc1` as SMILES string with (*Z*,*Z*)-configuration.  It is not the one COD currently states on the landing page of the entry, but leads to an equivalent representation in e.g., CDK Depict and OpenBabel.

**Comment by baoilleach** [comment] 2021-11-21 09:34
I'm going to close this bug report as the code is working as intended, and OB is correct to report a problem with the SMILES string. Whatever software generated the SMILES should be informed of the problem. The interpretation of up/down bond symbols associated with ring closures is confusing. I was about to write a blog post on the topic and then I found I already had, though the example here is perhaps more complicated than the one here:
https://baoilleach.blogspot.com/2010/09/are-you-on-my-side-or-not-its-ez-part.html

**Closed by baoilleach** 2021-11-21 09:34 UTC

**Comment by merkys** [comment] 2021-11-22 13:20
Answering to @baoilleach first. The source of the SMILES in question is manual creation.

Thank you for sharing the link to your blog post. The following sentence from it is new to me:

> Note that the symbol used for the ring opening is the opposite of that for the ring closure.

This seems to be in conflict with the [OpenSMILES specification](http://opensmiles.org/opensmiles.html#ringclosure) which says:

> If a bond symbol is present between the atom and rnum, it can be present on either or both bonded atoms. However, if it appears on both bonded atoms, the two bond symbols must be the same.

Thus I assumed `C(=O)(/C=C1\CN(CC/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC` to mean the same as `C(=O)(/C=C/1\CN(CC/1=C\c1ccccc1)S(=O)(=O)c1ccc(cc1)C)OC` (ring bond coming up from atom 4).
