### ISSUE TITLE
Setting score for OBConformerSearch results in segfault using Python bindings

### ISSUE THREAD

**Issue by dww100** [openbabel/openbabel#2221] opened 2020-05-15 14:26 UTC
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.0.0 and 3.1.0 (conda-forge labels `cf202003` and `main`)
Operating system and version: Ubuntu 18.04 

## Expected Behavior
Ability to set OBConformerSearch score inside and outside a function without a segfault.

## Actual Behavior
Setting score outside a function works at the time as expected but causes segfault later upon object deletion. Inside a function this segfault is instant.

## Steps to Reproduce

Working code:
```
from openbabel import openbabel, pybel

smiles = "c1c(N(=O)=O)cccc1"

mol = pybel.readstring("smi", smiles)
mol.addh()
mol.make3D()  
search = openbabel.OBConformerSearch()
x = openbabel.OBRMSDConformerScore()
search.SetScore(x)
search.Setup(mol.OBMol, 10)
search.GetConformers(mol.OBMol)
print(mol.OBMol.NumConformers())
```

Segfaulting code:

```
from openbabel import openbabel, pybel

smiles = "c1c(N(=O)=O)cccc1"

def make_conformers(smiles_string):
    mol = pybel.readstring("smi", smiles_string)
    mol.addh()
    mol.make3D()
    
    search = openbabel.OBConformerSearch()
    x = openbabel.OBRMSDConformerScore()
    search.SetScore(x)
    # search.Setup(mol.OBMol, 10)
    # search.GetConformers(mol.OBMol)
    # print(mol.OBMol.NumConformers())

make_conformers(smiles)
```

I have run the above code in a script and ipython which results in a blunt `Segmentation fault (core dumped)` and Jupyter which results in no output at all.

Only issue that looked potentially connected on a quick search was #2066.

**Comment by e-kwsm** [comment] 2020-05-15 15:16
> Setting score outside a function works as expected, inside a function this causes a segfault.

No, segfault also occurs in a global scope due to deletion of objects:

```python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbabel import openbabel, pybel
>>> 
>>> smiles = "c1c(N(=O)=O)cccc1"
>>> 
>>> mol = pybel.readstring("smi", smiles)
>>> mol.addh()
>>> mol.make3D()  
>>> search = openbabel.OBConformerSearch()
>>> x = openbabel.OBRMSDConformerScore()
>>> search.SetScore(x)
>>> exit()
zsh: segmentation fault  python3
```

**Comment by dww100** [comment] 2020-05-15 15:53
Updated the original report in line with your comment.

**Comment by e-kwsm** [comment] 2020-05-15 16:54
Seems to be a duplicate of #2066.

MWE can be narrowed into
```python
from openbabel import openbabel
search = openbabel.OBConformerSearch()
x = openbabel.OBRMSDConformerScore()
search.SetScore(x)
```

and the corresponding C++ code is:

```cpp
#include <openbabel/conformersearch.h>
int main() {
  auto search = OpenBabel::OBConformerSearch{};
  auto x = OpenBabel::OBRMSDConformerScore{};
  search.SetScore(&x);
}
```

Error `free(): invalid pointer` comes from

https://github.com/openbabel/openbabel/blob/650b1f829ac47cc84877a330366ec9485da3ec99/src/conformersearch.cpp#L327

and possibly from

https://github.com/openbabel/openbabel/blob/650b1f829ac47cc84877a330366ec9485da3ec99/include/openbabel/conformersearch.h#L335

**Closed** 2020-05-16 14:23 UTC
