### ISSUE TITLE
Alignment Question

### ISSUE THREAD

**Issue by mti193** [openbabel/openbabel#2087] opened 2019-11-18 18:20 UTC
Hi everyone. Just a quick question.

Basically I'm at the final part of my research and I don't really know what to do in terms of procedure.

Background:
I have SDF file with the 3d coordinates of every molecule of interest.

My ultimate goal is to take molecule A, align it to molecule B and then "delete" all atoms from molecule B and molecule A which are not present in each other. These aligned atoms of molecule B, will then be compared with the atoms from Molecule A and their differences in electronegativity will be calculated for the Molecules.

I have tried doing an MCS alignment but it can be 'broken easily' For example:

    Molecule A : CCCCSCCO
    Molecule B:  CCCCNCCO
    MCS :        CCCC
    Ideal alignment: CCCC_CCO
Problem: The CCO atoms are present in both but this method tends to 'lose' information. 

I have tried obfit:
    command: obfit SMART PATTERN MoleculeA.sdf MoleculeB.sdf > aligned.sdf
The input Smart Pattern is the MCS generated but the aligned.sdf contains the same atoms as Molecule B (atoms which aren't in common aren't removed).

What methods can I use which may assist with what I want/ What am i missing?

**Comment by ghutchis** [comment] 2019-11-18 21:45
This is not a bug report. Please send to the openbabel-discuss@lists.sf.net mailing list.

 I'm going to close this.

**Closed by ghutchis** 2019-11-18 21:45 UTC
