### ISSUE TITLE
Can't set charges if OBMol is created programmatically

### ISSUE THREAD

**Issue by yesint** [openbabel/openbabel#1817] opened 2018-04-13 16:38 UTC
The following simple example code models much more complex situation when OBMol have to be created programmatically from the data stored in the format of other molecular modeling tookit. 
- It reads existing mol2 file to get some data (in real example data come from other toolkit)
- It creates empty OBMol and populates it with data
- It writes obtained file back in mol2 format
The problem is that setting partial charges in such OBMol object makes no effect at all - the written file always have zero charges.

```
#include <iostream>
#include <openbabel/obconversion.h>
#include <openbabel/mol.h>
#include <openbabel/atom.h>
#include <openbabel/residue.h>


using namespace std;

int main(int argc,char **argv)
{
  OpenBabel::OBConversion conv;
  OpenBabel::OBMol mol;
  conv.ReadFile(&mol, "mhc-opt.mol2");
  
  OpenBabel::OBMol newmol;
  
  OpenBabel::OBResidue obr;
  
  FOR_ATOMS_OF_MOL(ba, mol)
    {
        OpenBabel::OBAtom oba;
        
        auto n = ba->GetAtomicNum();
        oba.SetAtomicNum(n);
        
        auto v = ba->GetVector();
        oba.SetVector(v);
        
        float c = ba->GetPartialCharge();
        oba.SetPartialCharge(c);
        
        newmol.AddAtom(oba);
        
        obr.SetName("RES");
        obr.SetNum(1);
        obr.SetChain('A');
        obr.AddAtom(&oba);
        obr.SetAtomID(&oba, ba->GetResidue()->GetAtomID(&(*ba)));        
    }
    newmol.AddResidue(obr);
    
    
    FOR_ATOMS_OF_MOL(ba, newmol)
    {
        ba->SetPartialCharge(1.0); // These charges are NOT actually set!
    }
    
    conv.WriteFile(&newmol,"out.mol2"); // Writes zero charges
    
  return 0;
}
```

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: latest git
Operating system and version: Linux Mint 18.3

## Expected Behavior
Generated file have to contain charges set programmatically in the code

## Actual Behavior
Generated file have zero charges regardless of what I set in the code

## Steps to Reproduce
The code above compiled as:
g++  ob.cpp -I/usr/include/openbabel-2.0/ -L/usr/lib/openbabel/2.4.90/ -lopenbabel -lstdc++ -O3 -std=c++11

Input file:
[mhc-opt.zip](https://github.com/openbabel/openbabel/files/1908220/mhc-opt.zip)

**Comment by bbucior** [comment] 2018-04-20 14:11
In your example code, I was able to get the charges to work (1.0, or the original charges) by adding the line `newmol.SetPartialChargesPerceived();` before writing the output file.

**Comment by baoilleach** [comment] 2018-04-24 13:27
Thanks @bbucior. It looks like the code is working as intended. Lazily-evaluated properties (e.g. aromaticity or partial charges) need to be marked as perceived if you want to avoid the lazy evaluation. The "normal" situation is that you call GetPartialCharge() on an atom, and if not marked as perceived it triggers the evaluation across the whole molecule, assigns the values via SetPartialCharge() and then marks the property as perceived. If you set values "manually", then you also need to mark the molecule as having partial charges already perceived.

I'm marking as closed, but feel free to reopen.

**Closed by baoilleach** 2018-04-24 13:27 UTC
